### ISSUE TITLE
scrolling with the trackpad

### ISSUE THREAD

**Issue by nilsbecker** [nojb/llpp#6]
two-finger scrolling with the trackpad works but is too fast (too large increments). also, when scrolling left/right, it scrolls up/down instead

**Comment by nojb** [comment]
Yes, it would be nice to have a nice smooth inertial scrolling (I am currently working on this).  Horizontal scrolling is not yet enabled but should be soon.  Thanks!

**Comment by nojb** [comment]
I commited cec1a7515a67a85059af6f5bb2d8865246964aa4 and I think it is working much better now (vertical scrolling only).  Could you give it a go and tell me what you think ?  Thanks!

**Comment by nilsbecker** [comment]
it's better but not yet perfect. i find it a bit laggy. e.g. if you scroll up-down-up-down in a continuous oscillating way you will notice a lag. compare that e.g. to Preview where the feeling is more similar to directly touching a piece of paper and moving it up and down. i don't know exactly why this is. maybe the inertia should only be felt once the trackpad is released?

**Comment by nojb** [comment]
Yes, I noticed - I am investigating how to fix the lag.

**Comment by nilsbecker** [comment]
another thing: when the help screen is open, the trackpad still scrolls the document, not the help screen

**Comment by nojb** [comment]
I think vertical scrolling should be fixed now.  I will look at horizontal scrolling and the help screen issue now.

**Comment by nojb** [comment]
Horizontal trackpad scrolling should also be OK now (but still working on the finishing touches).

**Comment by nilsbecker** [comment]
i tried it out, it's impressive! scrolling both ways is working fine now. the pinch zoom works with some restrictions

1. flickering during zooming.
 i guess making this smooth would require some scaling tricks; this sounds like a major thing. a simpler solution may be to only draw a frame during the actual zooming motion

2. centering 
during zoom, the page moves sideways. ideally, the point to which the mouse pointer points :) should stay fixed during a zoom.

**Comment by nojb** [comment]
Thanks for the feedback.  Both 1. and 2. are noted.  1. may be a little difficult to implement with the current architecture - will have to investigate more.  2. should be doable; will look into it.

**Comment by nilsbecker** [comment]
the off-center page position (2.) also appears when jumping to search results

**Comment by nilsbecker** [comment]
for 1., i was thinking this: already now, the display switches to a checkerboard pattern while the rendering is not complete. problem is, it tries to complete rendering at all times during a zoom. the only thing needed would be to tell it to wait with the rendering until the zoom is released. i guess this is upstream in mupdf?

**Comment by nojb** [comment]
I am not sure - I think this is something that could be done in the general rendering code of `llpp`.
@moosotc:  would it be possible to signal the main module so that the only the checkerboard pattern is drawn between zoom start/end ?

**Comment by moosotc** [comment]
Nicolas Ojeda Bar <notifications@github.com> writes:

> I am not sure - I think this is something that could be done in the
> general rendering code of `llpp`.
> @moosotc: would it be possible to signal the main module so that the
> only the checkerboard pattern is drawn between zoom start/end ?

There are two ways to interpret this question:
 a. nothing in the region is ready
 b. not everything in the region is ready

a - there's no such a function currently, easy enough to do
b - main.ml:layoutready

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
@nilsbecker regarding flickering when pinch zooming, you can try setting the throttle parameter in the info screen to something ('inf' for instance, or some number) this will alleviate the problem somewhat.

btw @nojb, it appears that '.' key is not working (at least during textentry) (throttle takes floating point argument and I was unable to enter .5 for instance (to delay the redisplay for a half a second if there are tiles in the layout that are not ready yet))

**Comment by nojb** [comment]
Thanks - I will look into it.

**Comment by nilsbecker** [comment]
i can confirm the `.` problem. nevertheless i tried setting throttle to 1s and this completely fixes the flickering for me (!) now it's just like Preview

**Comment by moosotc** [comment]
@nilsbecker regarding scrolling while in the help (actually any) mode other than view, the code does exactly what you've coded. IOW you do not invoke current ioh's scroll method but do it manually, so the result is something to be expected

**Comment by nojb** [comment]
Thanks @moosotc , I had actually realized this - I was about to fix this as soon as I had some free time to do it.

By the way

ioh = ?

**Comment by moosotc** [comment]
Nicolas Ojeda Bar <notifications@github.com> writes:

> Thanks @moosotc , I had actually realized this - I was about to fix
> this as soon as I had some free time to do it.
>
> By the way
>
> ioh = ?
>

ioh = input output handler, IMMSM (if my memory serves me)

-- 
mailto:moosotc@gmail.com

**Comment by nojb** [comment]
Trackpad scrolling (only vertical for now) in help/info/etc. pages should now be working.

**Comment by nilsbecker** [comment]
trackpad scrolling in help does work now for me. zoom centering not yet.

**Comment by nilsbecker** [comment]
throttling for fixing the flickering: i have to correct myself, it't working but not perfectly. whenever the pinch zoom starts, there is a single flicker. then the rest of the flicker motion is smooth.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> throttling for fixing the flickering: i have to correct myself, it't
> working but not perfectly. whenever the pinch zoom starts, there is a
> single flicker. then the rest of the flicker motion is smooth.
>

I guess this is specific to pinch zoom somehow, given that I've tried
with external usb mouse and wheel zooming and also with ctrl-+/- and
can't notice flickering. (@nojb btw. had to change the ctrl-mouse wheel
to alt-... since ctrl one clashes with "OS wide" zooming).

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> throttling for fixing the flickering: i have to correct myself, it't
> working but not perfectly. whenever the pinch zoom starts, there is a
> single flicker. then the rest of the flicker motion is smooth.
>

Can you please test if following improves the situation at all?

diff --git a/main.ml b/main.ml
index 87f4a8c..5f8ae23 100644
--- a/main.ml
+++ b/main.ml
@@ -5509,7 +5509,10 @@ let postdrawpage l linkindexbase =
           List.iter (fun vals -> drawprect opaque x y vals);
         let n = postprocess opaque hlmask x y (linkindexbase, s, conf.hfsize) in
         if n < 0
-        then (state.redisplay <- true; 0)
+        then (
+          if conf.maxwait != None then state.redisplay <- true;
+          0
+        )
         else n
       else 0
   | _ -> 0


-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
we have the patch formatting problem again. i cannot successfully paste this either from the email or from the web. it should be possible to attach a file via the web interface of github though.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:



> we have the patch formatting problem again. i cannot successfully
> paste this either from the email or from the web. it should be
> possible to attach a file via the web interface of github though.
>

Wonder if this would work (attached).

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> nilsbecker <notifications@github.com> writes:
>
>
>
>> we have the patch formatting problem again. i cannot successfully
>> paste this either from the email or from the web. it should be
>> possible to attach a file via the web interface of github though.
>>
>
> Wonder if this would work (attached).

Apparently not. http://boblycat.org/~malc/another.patch

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ok, that worked. i was able to apply and recompile. unfortunately the single-flicker behavior is unchanged.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok, that worked. i was able to apply and recompile. unfortunately the
> single-flicker behavior is unchanged.
>

Then I will need your llpp.conf to match your settings and document plus
precise description of what you are doing to get the flicker...

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
i retried with a blank llpp.conf. i am using this random document.
[altafini02.pdf](https://github.com/nojb/llpp/files/383758/altafini02.pdf)

i am on an imac now, with bluetooth trackpad. can't test on macbook at the moment. what i see is this:

without throttling: a lot of checkerboard flickering during pinch

with throttling: a single flicker at the start of the pinch zoom motion. however, this happens only about 50% of the time.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> i retried with a blank llpp.conf. i am using this random document.
> [altafini02.pdf](https://github.com/nojb/llpp/files/383758/altafini02.pdf)
>
> i am on an imac now, with bluetooth trackpad. can't test on macbook at
> the moment. what i see is this:
>
> without throttling: a lot of checkerboard flickering during pinch
>
> with throttling: a single flicker at the start of the pinch zoom
> motion. however, this happens only about 50% of the time.
>

Thanks, I'll see what can be done.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> i retried with a blank llpp.conf. i am using this random document.
> [altafini02.pdf](https://github.com/nojb/llpp/files/383758/altafini02.pdf)
>
> i am on an imac now, with bluetooth trackpad. can't test on macbook at
> the moment. what i see is this:
>
> without throttling: a lot of checkerboard flickering during pinch
>
> with throttling: a single flicker at the start of the pinch zoom
> motion. however, this happens only about 50% of the time.
>

Can you try this hack? (not yet sure what's going on here)
http://boblycat.org/~malc/ya.patch

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ok, i tried now on a macbook. first with the unpatched master: same once-flicker problem. then with the patch above. two things happened: the history display does not work when llpp is started without a file argument. and, the flickering stops! nice!

now the only problems that remain are the centering when zooming, and the fact that when zooming out far, pages get separated more and more.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok, i tried now on a macbook. first with the unpatched master: same
> once-flicker problem. then with the patch above. two things happened:
> the history display does not work when llpp is started without a file
> argument. and, the flickering stops! nice!

After spending considerable amount of time with this I finally
understood what's going on under the hood,
f84e2ddc7530d8b7879f0ad868d8de8d2fa36232 while fixing one thing
introduced this flickering regression. Thanks for pushing with this
thing - the issue is real. I sure hope that
http://boblycat.org/~malc/patch3.patch will work just as well, history
display should be working.

>
> now the only problems that remain are the centering when zooming, and
> the fact that when zooming out far, pages get separated more and more.
>

I am not sure what you mean by pages get separated though.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
> I am not sure what you mean by pages get separated though.

when zooming out to the point that more than one page fits on a screen, i would expect that pages get smaller and the separation distance between pages also gets smaller proportionally, so that e.g. they remain separated by 5% of the page height. in that way, zooming out feels like moving away from the pages arranged as a column, in z direction.

what happens currently is that pages get smaller but the separation of page centers stays constant -- eventually this leads to tiny pages that are separated by comparatively large spaces.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

>> I am not sure what you mean by pages get separated though.
>
> when zooming out to the point that more than one page fits on a
> screen, i would expect that pages get smaller and the separation
> distance between pages also gets smaller proportionally, so that
> e.g. they remain separated by 5% of the page height. in that way,
> zooming out feels like moving away from the pages arranged as a
> column, in z direction.
>
> what happens currently is that pages get smaller but the separation of
> page centers stays constant -- eventually this leads to tiny pages
> that are separated by comparatively large spaces.
>

The interpagespace stays constant in "normal mode" and it's whatever is
needed (to show exactly one page) in "presentation mode". What you want
is something entirely different and I believe it would require non
trivial ammount of code to implement.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ah, ok. i just checked again i think i was just seeing the 'presentation mode' zooming behavior. out of presentation mode, everything works as i imagined it should. so everything's fine. please disregard my page spacing comment. 

so then the only thing that is still not ideal is the missing centering while zooming.

**Comment by nojb** [comment]
Yes, I have not forgotten about this.  I am currently on travel which is why I haven't made much progress on this.  I played a little with it but have not yet figured out the right combination of zooming and scrolling to leave the zoom point fixed (note that the behaviour is different if the pdf page width fits inside in the window or not).

**Comment by nojb** [comment]
Closing this since all other points have been resolved and opening a dedicated issue about the zooming.

**Comment by moosotc** [comment]
@nilsbecker btw can you try pinch zooming without throttling but with llpp invoked with -wtmode command line option [1]  just want to collect some more data

[1] (not that I should recommend either of them - gross hacks and I'm of the mind of ripping the related code out as it's very very subtle)
